### ISSUE TITLE
[Disposable] закрытие хэндлов при (нештатном) завершении процесса

### ISSUE THREAD

**Issue by VjacheslavVytjagov** [mumusan/dotnetbook#21]
Вы пишете: "...либо заблокируете на долгое время файл на файловой шаре, если он был открыт через средства ОС, но не был закрыт. Пример с файловыми шарами особенно хорош, потому что блокировка останется даже после закрытия приложения: открытость файла регулирует та сторона, на которой он находится. А удаленная сторона не получит сигнала закрытия файла, если вы его не закрыли самостоятельно.".

Однако известно, что в Windows при завершении процесса, штатном или нештатном, все незакрытые хэндлы закрываются. Отвечает за это сама операционная система. Работает это через таблицу хэндлов, которая ассоциирована с процессом. Вот что про это пишет Рихтер (http://wm-help.net/books-online/book/59464/59464-22.html): "А вдруг Вы забыли вызвать CloseHandle — будет ли утечка памяти? И да, и нет. Утечка ресурсов (тех же объектов ядра) вполне вероятна, пока процесс еще исполняется. Однако по завершении процесса операционная система гарантированно освобождает все ресурсы, принадлежавшие этому процессу, и в случае объектов ядра действует так: в момент завершения процесса просматривает его таблицу описателей и закрывает любые открытые описатели.".  Поскольку в основе .NET процесса все равно лежит нативный процесс, я не вижу причин, почему в .NET должно  быть отличное поведение хэндлов.

**Comment by mumusan** [comment]
Да, это вопрос известный. Но я получал ситуации, когда блокировалась файловая шара и мне приходилось писать письма админам чтобы они снимали блокировку :)

**Comment by mumusan** [comment]
Я переписал это место чтобы стало понятно что я имел ввиду. Согласен, ввел в заблуждение. Спасибо!
